name: Deploy zipped site to GitHub Pages

on:
  push:
    branches: ["maestro", "master", "main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List repo (debug)
        run: ls -la

      - name: Ensure ZIP exists
        run: |
          test -f site.zip || (echo "site.zip not found in repo root" && exit 9)

      - name: Unzip site.zip
        run: |
          mkdir -p site
          unzip -o site.zip -d site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4
