name: Implementar un sitio comprimido en GitHub Pages

on:
  push:
    branches: ["maestro", "principal", "master"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar
        uses: actions/checkout@v4

      - name: Descomprimir site.zip
        run: |
          mkdir site && unzip -o site.zip -d site

      - name: Subir artefacto
        uses: actions/upload-pages-artifact@v2
        with:
          path: site

      - name: Implementar en páginas
        id: deployment
        uses: actions/deploy-pages@v2
